# Generated by Django 4.2 on 2023-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stdId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('extractText', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='FilesData')),
            ],
        ),
    ]
