# Generated by Django 4.2 on 2023-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='docxText',
            field=models.TextField(null=True),
        ),
    ]
